### ISSUE TITLE
job 功能实现后还继续开源吗

### ISSUE THREAD

**Issue by wxiao1002** [ruffjs/tio#1]
你好，我尝试了下你们的demo ，想问下job 功能排期什么时候实现，到时候开源不？

**Comment by ogofly** [comment]
> 你好，我尝试了下你们的demo ，想问下job 功能排期什么时候实现，到时候开源不？

1. `job` 模块做完会一并开源出来。 我们内部项目用的和这个github仓库的东西是同一份。
2. 暂无具体排期。 目前对 job 的设计上还在功能性和简单性方面找平衡点。

描述下你们用 job 想解决的问题或场景？方便设计时加一考虑。

**Comment by wxiao1002** [comment]
好的，job 功能目前想解决的问题是 
- 定时控制设备
- 手工配置定时采集数据

**Comment by ogofly** [comment]
> 好的，job 功能目前想解决的问题是
> 
> * 定时控制设备
> * 手工配置定时采集数据

在 job 出来之前，触发控制或采集的`事件`或`定时逻辑`如果是服务端主导的，也可以考虑使用设备`直接方法`调用。  
但，如果这些事件或逻辑是设备也方便获知的，建议通过`Shadow`或`直接方法`下发配置给设备后在设备侧实现定时，具体根据你需求。
